---

- name: Config firewalld
  block:
    - name: Config firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: create directory for nginx files
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root