---
  php_packages:
    - php
    - php-common
    - php-intl
    - php-fpm
    - php-mysqlnd
    - php-json
    - php-opcache
    - php-mbstring
    - php-xml
    - php-gd
    - php-curl

  nginx: nginx