---

- name: Config php
  block:
    - name: Put correct php.ini
      template:
        src: templates/php.ini.j2
        dest: /etc/php.ini

    - name: Put correct www.conf
      template:
        src: templates/www.conf.j2
        dest: /etc/php-fpm.d/www.conf
      notify:
        - reload php-fpm
